import setuptools


setuptools.setup(
    name="rvc_pkg",
    packages=setuptools.find_namespace_packages(),
    version="0.1.3",
    author="lj1995",
    description="An easy-to-use Voice Conversion framework based on VITS",
    url="https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI",
    project_urls={},
    scripts=[],
    include_package_data=True,
    # include JSON files
    package_data={
        "": ["*.json"],
    },
    install_requires=[
        "absl-py",
        "audioread",
        "av",
        "colorama",
        "Cython",
        "fairseq", # 0.12.2 remove restriction due to installation issues
        "faiss-gpu",
        #"faiss-cpu",
        # "fastapi==0.88", # Unnecessary for package use
        "ffmpeg-python",
        "ffmpy",
        "fsspec",
        # "gradio==3.34.0", # Unnecessary for package use
        "httpx",
        "Jinja2",
        "joblib",
        "json5",
        "librosa",
        "llvmlite",
        "Markdown",
        "matplotlib-inline",
        "matplotlib",
        "numba",
        "numpy==1.23.5", # last float attribute version
        "onnxruntime-gpu; sys_platform != 'darwin'",
        "onnxruntime; sys_platform == 'darwin'",
        "Pillow",
        "praat-parselmouth",
        "pyasn1-modules",
        "pyasn1",
        "pydub",
        "python-dotenv",
        "pyworld",
        "PyYAML",
        "resampy",
        "scikit-learn",
        "scipy",
        "soundfile",
        "sympy",
        "tabulate",
        "tensorboard",
        "tensorboardX",
        "torchcrepe",
        "torchfcpe",
        "tornado",
        "tqdm",
        "uc-micro-py",
        "uvicorn",
        "Werkzeug",
    ],
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
)
